//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InterConnect
    {
        public string CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string NIT { get; set; }
        public Nullable<decimal> LIMITE_CREDITO { get; set; }
        public Nullable<int> TMP { get; set; }
        public Nullable<int> ANT { get; set; }
        public Nullable<int> FACT { get; set; }
    }
}
